# Boolean Truth Table Practice

print(True and True, True)
print(False and True, False)
print(1 == 1 and 2 == 1, False)
print("test" == "test", True)
print(1 == 1 or 2 != 1, True)
print(True and 1 == 1, True)
print(False and 0 != 0, False)
print(True or 1 == 1, True)
print("test" == "testing", False)
print(1 != 0 and 2 == 1, False)
print("test" != "testing", True)
print("test" == 1, False)
print(not(True and False), True)
print(not(1 == 1 and 0 != 1), False)
print(not(10 == 1 or 1000 == 1000), False)
print(not(1 != 10 or 3 == 4), False)
print(not("testing" == "testing" and "Zed" == "Cool Guy"), True)
print(1 == 1 and not("testing" == 1 or 1 == 0), True)
print("chunky" == "bacon" and not(3 == 4 or 3 == 3), False)
print(3 == 3 and (not("testing" == "testing" or "Python" == "Fun")), False)

# # Boolean Truth Table Fixed so all are true

# print(True and True)
# print(False and True)
# print(1 == 1 and 2 == 1)
# print("test" == "test")
# print(1 == 1 or 2 != 1)
# print(True and 1 == 1)
# print(False and 0 != 0)
# print(True or 1 == 1)
# print("test" == "testing")
# print(1 != 0 and 2 == 1)
# print("test" != "testing")
# print("test" == 1)
# print(not(True and False))
# print(not(1 == 1 and 0 != 1))
# print(not(10 == 1 or 1000 == 1000))
# print(not(1 != 10 or 3 == 4))
# print(not("testing" == "testing" and "Zed" == "Cool Guy"))
# print(1 == 1 and not("testing" == 1 or 1 == 0))
# print("chunky" == "bacon" and not(3 == 4 or 3 == 3))
# print(3 == 3 and (not("testing" == "testing" or "Python" == "Fun")))
